### ISSUE TITLE
Possible "http: multiple response.WriteHeader calls"

### ISSUE THREAD

**Issue by cosminilie** [laicosly/restiful#1]
I've been experimenting with a similar approach however it seems to me that one possible issue is getting: "http: multiple response.WriteHeader calls" if one or more handlers down the chain write to "w" and one of them returns an error. In that case both the handlers and the error will try to write to w causing this issue. I haven't tested this so i could be way off. 

Also given this problem the http status code for the error written will always be 200 OK. I guess this is a matter of opinion.

**Comment by cosminilie** [comment]
I'm not saying this is a bug, it's just that people should be aware of this.

**Comment by ghost** [comment]
Good point, but I think that this is true for potentially any http implementation.  The restiful package doesn't get in the developer's way there, and asserts no opinion.
